# Generated by Django 6.0.5 on 2026-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('harga', models.IntegerField()),
            ],
        ),
    ]
